version: '{branch}-{build}'
image: Visual Studio 2017
environment:
  GH_TOKEN:
    secure: 1aigA+tF1hWwZVVARvg+fhwGlJmgNLfs4FDdlgW8mOWqe9MA+gjKLgKT99wO4D0e
install:
  - ps: Install-Product node 8 x64
  - cmd: yarn
build: off
test_script:
  - cmd: yarn lint
  - cmd: yarn test
deploy_script:
  - cmd: yarn run dist --x64