version: '{branch}-{build}'
os: unstable
for:
-
  branches:
    only:
      - master
  environment:
    GH_TOKEN:
      secure: 1aigA+tF1hWwZVVARvg+fhwGlJmgNLfs4FDdlgW8mOWqe9MA+gjKLgKT99wO4D0e
install:
  - ps: Install-Product node 8 x64
  - cmd: yarn
  - cmd: yarn global add codecov
build: off
test_script:
  - cmd: yarn lint
  - cmd: yarn cover
after_test:
  - cmd: codecov
deploy_script:
  - cmd: yarn run dist --x64