version: '{branch}-{build}'
image: Visual Studio 2017
environment:
  nodejs_version: "8"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - cmd: yarn
build_script:
  - cmd: yarn dist
test: off
deploy:
  - provider: GitHub
    auth_token:
      secure: 1aigA+tF1hWwZVVARvg+fhwGlJmgNLfs4FDdlgW8mOWqe9MA+gjKLgKT99wO4D0e
    artifact: release-builds/*.*
    draft: true