version: '{branch}-{build}'
image: Visual Studio 2017
environment:
  GH_TOKEN:
    secure: 1aigA+tF1hWwZVVARvg+fhwGlJmgNLfs4FDdlgW8mOWqe9MA+gjKLgKT99wO4D0e
install:
  - ps: Install-Product node 8 x64
  - cmd: yarn
build_script:
  - cmd: yarn dist --ia32 --x64
test: off